apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: cloudops
spec:
  replicas: 2
  selector:
    matchLabels: { app: backend }
  template:
    metadata:
      labels: { app: backend }
    spec:
      containers:
      - name: backend
        image: omryakawar/cloudops-backend:latest
        envFrom:
        - secretRef:
            name: backend-secrets