apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: cloudops
spec:
  replicas: 2
  selector:
    matchLabels: { app: backend }
  template:
    metadata:
      labels: { app: backend }
    spec:
      containers:
      - name: backend
        image: omryakawar/cloudops-backend:latest
        ports:
        - containerPort: 3001
env:
 - name: MONGO_URI
   value: "mongodb://mongo-0.mongo.cloudops.svc.cluster.local:27017/cloudops"
 - name: APP_NAME
   value: "cloudops-platform"
 - name: APP_ENV
   value: "dev"
 - name: APP_VERSION
   value: "1.0.0"
 - name: PORT
   value: "3001"
