version: '3.9'

services:
  mongo:
    image: mongo:7
    container_name: mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  backend:
    image: omryakawar/cloudops-backend:latest
    container_name: cloudops-backend
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - APP_ENV=prod
      - APP_NAME=cloudops-platform
      - APP_VERSION=1.0.0
      - MONGO_URI=mongodb://mongo:27017/cloudops
    depends_on:
      - mongo

  frontend:
    image: omryakawar/cloudops-frontend:latest
    container_name: cloudops-frontend
    ports:
      - "80:80"
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://<ec2 public ip>:3001
    depends_on:
      - backend

volumes:
  mongo_data:
