apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backend-secrets
  namespace: cloudops
spec:
  secretStoreRef:
    name: aws-secrets
    kind: SecretStore
  target:
    name: backend-secrets
  data:
    - secretKey: MONGO_URI
      remoteRef:
        key: cloudops/backend
        property: MONGO_URI
