apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: cloudops
spec:
  replicas: 2
  selector:
    matchLabels: { app: frontend }
  template:
    metadata:
      labels: { app: frontend }
    spec:
      containers:
      - name: frontend
        image: omryakawar/cloudops-frontend:latest
        ports:
        - containerPort: 3000
        
