apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backend-secrets
  namespace: cloudops
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets
    kind: SecretStore

  target:
    name: backend-secrets
    creationPolicy: Owner

  data:
    - secretKey: PORT
      remoteRef:
        key: cloudops/backend
        property: PORT

    - secretKey: APP_ENV
      remoteRef:
        key: cloudops/backend
        property: APP_ENV

    - secretKey: APP_NAME
      remoteRef:
        key: cloudops/backend
        property: APP_NAME

    - secretKey: APP_VERSION
      remoteRef:
        key: cloudops/backend
        property: APP_VERSION

    - secretKey: MONGO_URI
      remoteRef:
        key: cloudops/backend
        property: MONGO_URI
